[package]
name = "job-hunter-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
job-hunter-core = { path = "../core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }